### ISSUE TITLE
After using bfconvert extracting the leica.scn layer, the layer becomes rose red

### ISSUE THREAD

**Issue by DuangduangChen** [VolkerH/Tutorial-on-bftools-and-bfconvert#1]
This is what I'm typing into linux:
./bftools/bfconvert -debug -tilex 512 -tiley 512 -series 0 -compression LZW    leica.scn   leica_MAX/leica.tif
Here is the link to the rose red image：
https://github.com/DuangduangChen/DuangduangChen/blob/main/leica.tif

It works, but it has a problem. This is part of the debug message
No update needed
leica.scn
### Could not find loci.formats.in.SlideBook6Reader
java.lang.ClassNotFoundException: loci.formats.in.SlideBook6Reader
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
        at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
        at java.base/java.lang.Class.forName(Class.java:315) ~[na:na]
        at loci.formats.ClassList.parseLine(ClassList.java:196) ~[bioformats_package.jar:5.6.0]
        at loci.formats.ClassList.parseFile(ClassList.java:258) ~[bioformats_package.jar:5.6.0]
        at loci.formats.ClassList.<init>(ClassList.java:138) ~[bioformats_package.jar:5.6.0]
        at loci.formats.ClassList.<init>(ClassList.java:122) ~[bioformats_package.jar:5.6.0]
        at loci.formats.ImageReader.getDefaultReaderClasses(ImageReader.java:79) ~[bioformats_package.jar:5.6.0]
        at loci.formats.ImageReader.<init>(ImageReader.java:116) ~[bioformats_package.jar:5.6.0]
        at loci.formats.tools.ImageConverter.testConvert(ImageConverter.java:346) ~[bioformats_package.jar:5.6.0]
        at loci.formats.tools.ImageConverter.main(ImageConverter.java:884) ~[bioformats_package.jar:5.6.0]
processor is INTEL_64 os.arch is amd64
architecture is LINUX_64 os.name is linux
architecture is LINUX_64 os.name is linux
platform specific path is META-INF/lib/linux_64/
mappedLib is libturbojpeg.so

**Comment by DuangduangChen** [comment]
bftools > 6 can make it

**Comment by VolkerH** [comment]
Only saw this now, more than 2 years later.
Good to see you managed to solve it.
Seems like this was more of an issue with bfconvert itself rather than the tutorial here, will close
